name: 'run-maestro'
description: 'draft'

inputs:
  apk-path:
      description: 'Path to the APK'
      required: true
  command:
    description: 'Command to run on maestro (e.g. maestro {command})'
    required: true
  test-name:
    description: 'Name of the maestro test. The report will have this name.'
    required: false
    default: 'maestro-test'
  bit-rate:
    description: 'Bit rate for the screenrecord command'
    required: false
    default: '3000000'
  video-res:
    description: 'Resolution of the recorded video'
    required: false
    default: '360x780'

runs:
  using: "composite"
  steps:
    - name: Install Maestro
      shell: bash
      run: |
        curl -fsSL "https://get.maestro.mobile.dev" | bash
        export PATH="$PATH":"$HOME/.maestro/bin"
        maestro --version

#todo: disable this step on mac machines
    - name: Enable KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        profile: pixel_6_pro
        ram-size: 8000M
        heap-size: 600M
        arch: x86_64
        disable-animations: true
        target: playstore
        script: |
          #!/bin/bash

          adb install ${{ inputs.apk-path }}
    
          # Start screen recording with inputs for bit-rate and video resolution
          adb shell "screenrecord --bugreport --size ${{ inputs.video-res }} --bit-rate ${{ inputs.bit-rate }} /data/local/tmp/maestro.mp4 & echo \$! > /data/local/tmp/screenrecord_pid.txt" &

          # Run Maestro tests. Still needs to capture the exit status without stopping the script.
          $HOME/.maestro/bin/maestro ${{ inputs.command }} || true

          # Stop screen recording and pull the video file
          adb shell "kill -2 \$(cat /data/local/tmp/screenrecord_pid.txt)" || true
          sleep 1
          adb pull /data/local/tmp/maestro.mp4 /home/runner/.maestro/tests/ || true
          

    - name: Move test
      shell: bash
      run: mv /home/runner/.maestro/tests ~

    - name: Upload report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: "report-${{ inputs.test-name }}"
        path: | 
          ~/tests/**/*
          ~/report_${{ inputs.test-name }}.xml
