# This task expects an artifact android-beta to be available in the workflow.
# It downloads the APK, installs Maestro, and runs the tests in the Android emulator.
# The test results are saved in a JUnit XML file and the video is saved in the tests directory.

name: 'run-maestro'
description: 'Run a given Maestro flow/subflow in the Android emulator. Tha action outputs a report and a video.'

inputs:
  test-name:
      description: 'Name of the maestro test'
      required: true
  test-path:
      description: 'Path to the Maestro test (It can be a single flow or a floder)'
      required: true
  bit-rate:
    description: 'Bit rate for the screenrecord command'
    required: false
    default: '3000000'
  video-res:
    description: 'Resolution of the recorded video'
    required: false
    default: '360x780'
  extra-args:
    description: 'Maestro extra arguments (e.g --include-tags)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Download APK
      uses: actions/download-artifact@v4
      with:
        name: android-beta
        path: androidApp/build/outputs/apk/beta/appDistribution

    - name: Rename APK
      shell: bash
      run: | 
        mv androidApp/build/outputs/apk/beta/appDistribution/androidApp-beta-appDistribution.apk maestro/app.apk
        ls maestro/

    - name: Install Maestro
      shell: bash
      run: |
        curl -fsSL "https://get.maestro.mobile.dev" | bash
        export PATH="$PATH":"$HOME/.maestro/bin"
        maestro --version

    - name: Enable KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        profile: pixel_6_pro
        ram-size: 8000M
        heap-size: 600M
        arch: x86_64
        disable-animations: true
        target: playstore
        script: |
          #!/bin/bash

          adb install ./maestro/app.apk
          adb shell pm set-app-links --package com.upside.consumer.android.beta 1 www.getupside.com
          adb shell pm set-app-links --package com.upside.consumer.android.beta 1 getupside.com

          # Start screen recording with inputs for bit-rate and video resolution
          adb shell "screenrecord --bugreport --size ${{ inputs.video-res }} --bit-rate ${{ inputs.bit-rate }} /data/local/tmp/maestro.mp4 & echo \$! > /data/local/tmp/screenrecord_pid.txt" &

          # Run Maestro tests. Still needs to capture the exit status without stopping the script.
          $HOME/.maestro/bin/maestro test --format junit --output ~/report_${{ inputs.test-name }}.xml ${{ inputs.extra-args }} ${{ inputs.test-path }} -e appId=com.upside.consumer.android.beta || true

          # Stop screen recording and pull the video file
          adb shell "kill -2 \$(cat /data/local/tmp/screenrecord_pid.txt)" || true
          sleep 1
          adb pull /data/local/tmp/maestro.mp4 /home/runner/.maestro/tests/ || true
          

    - name: Move test
      shell: bash
      run: mv /home/runner/.maestro/tests ~

    - name: Upload report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: "report-${{ inputs.test-name }}"
        path: | 
          ~/tests/**/*
          ~/report_${{ inputs.test-name }}.xml
